def job_name = "${env.JOB_NAME}".split('/')[0]
def branch = "${env.JOB_NAME}".split('/')[1]
def pipelineDirectory = "/var/jenkins_home/pipeline_scripts"

pipeline {
        agent any
        options {
                disableConcurrentBuilds()
        }
        stages {
                stage('update pipeline') {
                        steps {
                                script {
                                        sh "git -C " + pipelineDirectory + " fetch"
                                        sh "git -C " + pipelineDirectory + " checkout -m ${branch}"
                                        sh "git -C " + pipelineDirectory + " reset --hard origin/${branch}"
                                }
                        }
                }
          stage('docker build') {
                        steps {
                                script {
                                        sh "cp " + pipelineDirectory + "/aspnetapp/Dockerfile ."
                                        sh "docker build . --build-arg APPLICATION=${job_name} -t ${env.REGISTRY_HOST}/${job_name}:master-v${env.BUILD_ID}"
                                }
                        }
                }
          }
  }
